// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lifts.sql

package sqlc

import (
	"context"
)

const createLift = `-- name: CreateLift :one
INSERT INTO lifts (lift_type, created_at)
VALUES (?, ?)
RETURNING id, lift_type, created_at, coaching_cue, coaching_diagnosis
`

type CreateLiftParams struct {
	LiftType  string
	CreatedAt string
}

func (q *Queries) CreateLift(ctx context.Context, arg CreateLiftParams) (Lift, error) {
	row := q.db.QueryRowContext(ctx, createLift, arg.LiftType, arg.CreatedAt)
	var i Lift
	err := row.Scan(
		&i.ID,
		&i.LiftType,
		&i.CreatedAt,
		&i.CoachingCue,
		&i.CoachingDiagnosis,
	)
	return i, err
}

const deleteLift = `-- name: DeleteLift :exec
DELETE FROM lifts WHERE id = ?
`

func (q *Queries) DeleteLift(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLift, id)
	return err
}

const getLift = `-- name: GetLift :one
SELECT id, lift_type, created_at, coaching_cue, coaching_diagnosis
FROM lifts
WHERE id = ?
`

func (q *Queries) GetLift(ctx context.Context, id int64) (Lift, error) {
	row := q.db.QueryRowContext(ctx, getLift, id)
	var i Lift
	err := row.Scan(
		&i.ID,
		&i.LiftType,
		&i.CreatedAt,
		&i.CoachingCue,
		&i.CoachingDiagnosis,
	)
	return i, err
}

const listLifts = `-- name: ListLifts :many
SELECT id, lift_type, created_at, coaching_cue, coaching_diagnosis
FROM lifts
ORDER BY created_at DESC
`

func (q *Queries) ListLifts(ctx context.Context) ([]Lift, error) {
	rows, err := q.db.QueryContext(ctx, listLifts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lift
	for rows.Next() {
		var i Lift
		if err := rows.Scan(
			&i.ID,
			&i.LiftType,
			&i.CreatedAt,
			&i.CoachingCue,
			&i.CoachingDiagnosis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
