// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Lift struct {
	ID                int64
	LiftType          string
	CreatedAt         string
	CoachingCue       sql.NullString
	CoachingDiagnosis sql.NullString
}
